--
-- PostgreSQL database cluster dump
--

-- Started on 2023-06-21 19:20:53

SET default_transaction_read_only = off;

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

--
-- Roles
--

CREATE ROLE postgres;
ALTER ROLE postgres WITH SUPERUSER INHERIT CREATEROLE CREATEDB LOGIN REPLICATION BYPASSRLS PASSWORD 'SCRAM-SHA-256$4096:xQpwzBVTFSlFwXNQW92K/g==$0ynYk2zt6oXMr/XYRq1r5bdB+BH431ZDWk57eN0cnZg=:1Uu18pybt6pb1u1EMDxLenrGPpgwCdACkg8UstkGEIE=';

--
-- User Configurations
--








--
-- Databases
--

--
-- Database "template1" dump
--

\connect template1

--
-- PostgreSQL database dump
--

-- Dumped from database version 15.3
-- Dumped by pg_dump version 15.3

-- Started on 2023-06-21 19:20:53

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

-- Completed on 2023-06-21 19:20:53

--
-- PostgreSQL database dump complete
--

--
-- Database "postgres" dump
--

\connect postgres

--
-- PostgreSQL database dump
--

-- Dumped from database version 15.3
-- Dumped by pg_dump version 15.3

-- Started on 2023-06-21 19:20:53

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 2 (class 3079 OID 16384)
-- Name: adminpack; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS adminpack WITH SCHEMA pg_catalog;


--
-- TOC entry 3346 (class 0 OID 0)
-- Dependencies: 2
-- Name: EXTENSION adminpack; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION adminpack IS 'administrative functions for PostgreSQL';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 216 (class 1259 OID 16403)
-- Name: cuenta; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cuenta (
    id bigint NOT NULL,
    nombre_cuenta character varying(60),
    saldo double precision,
    saldo_limite double precision,
    limite_transferencia double precision,
    estado character varying(20),
    id_cuenta bigint NOT NULL,
    numero_cuenta character varying(60),
    moneda character varying(40)
);


ALTER TABLE public.cuenta OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16408)
-- Name: extracto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.extracto (
    id bigint NOT NULL,
    operacion character varying(60),
    observacion character varying(200),
    importe double precision,
    estado character varying(60),
    nro_cuenta character varying(60),
    fecha character varying(60)
);


ALTER TABLE public.extracto OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 16413)
-- Name: extracto_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.extracto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.extracto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 16398)
-- Name: persona; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.persona (
    id bigint NOT NULL,
    nombre character varying(60),
    apellido character varying(60),
    edad bigint,
    email character varying(60),
    telefono character varying(60)
);


ALTER TABLE public.persona OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16414)
-- Name: usuarios; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuarios (
    id bigint NOT NULL,
    id_persona bigint NOT NULL,
    usuario character varying(60),
    password character varying(60),
    estado character varying(30)
);


ALTER TABLE public.usuarios OWNER TO postgres;

--
-- TOC entry 3337 (class 0 OID 16403)
-- Dependencies: 216
-- Data for Name: cuenta; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cuenta (id, nombre_cuenta, saldo, saldo_limite, limite_transferencia, estado, id_cuenta, numero_cuenta, moneda) FROM stdin;
1	ITAU	4850000	8000000	4000000	Bloqueado	1	36529652	GUARANI
3	Continental	100	50	50	activo	3	123456789	DOLAR
4	BASA	1000	500	500	ACTIVO	4	123456333	DOLAR
2	VISION BANCO	5550450	8000000	4000000	ACTIVO	2	3652962	GUARANI
9	CONTINENTAL	5200050	5500000	3000000	Bloqueado	9	9	GUARANI
\.


--
-- TOC entry 3338 (class 0 OID 16408)
-- Dependencies: 217
-- Data for Name: extracto; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.extracto (id, operacion, observacion, importe, estado, nro_cuenta, fecha) FROM stdin;
8	DEPOSITO	Desposito Realizado	400	Procesado	6789	24/5/2023 12:04:00
9	RETIRO	Retiro Realizado	200	Procesado	6789	24/5/2023 12:05:40
10	TRANSFERENCIA	Transferencia realizada a la cuenta:  12345 	2	Procesado	6789	24/5/2023 12:06:04
11	RETIRO	Retiro Realizado	1	Procesado	12345	24/5/2023 12:07:57
12	DEPOSITO	Desposito Realizado	650000	Procesado	36529652	24/5/2023 17:11:20
13	RETIRO	Retiro Realizado	650000	Procesado	36529652	24/5/2023 17:12:47
14	TRANSFERENCIA	Transferencia realizada a la cuenta:  3652962 	350000	Procesado	36529652	24/5/2023 17:22:28
15	BLOQUEO	Cuenta bloqueada	0	Procesado	36529652	24/5/2023 17:24:40
16	DEPOSITO	Desposito Realizado	500	Procesado	3652962	21/6/2023 18:35:54
17	DEPOSITO	Desposito Realizado	500	Procesado	3652962	21/6/2023 18:46:05
18	RETIRO	Retiro Realizado	500	Procesado	3652962	21/6/2023 18:53:04
19	TRANSFERENCIA	Transferencia realizada a la cuenta:  9 	50	Procesado	3652962	21/6/2023 18:58:33
20	BLOQUEO	Cuenta bloqueada	0	Procesado	9	21/6/2023 19:04:52
\.


--
-- TOC entry 3336 (class 0 OID 16398)
-- Dependencies: 215
-- Data for Name: persona; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.persona (id, nombre, apellido, edad, email, telefono) FROM stdin;
8	Miguel	Benitez	21	Miguelbenitez@aj.com.py	0986319495
\.


--
-- TOC entry 3340 (class 0 OID 16414)
-- Dependencies: 219
-- Data for Name: usuarios; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuarios (id, id_persona, usuario, password, estado) FROM stdin;
1	1	Analia	45678	45678
4	4	string	string	string
1	5	Luuuca	123	123
\.


--
-- TOC entry 3347 (class 0 OID 0)
-- Dependencies: 218
-- Name: extracto_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.extracto_id_seq', 20, true);


--
-- TOC entry 3187 (class 2606 OID 16402)
-- Name: persona Persona_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.persona
    ADD CONSTRAINT "Persona_pkey" PRIMARY KEY (id);


--
-- TOC entry 3189 (class 2606 OID 16407)
-- Name: cuenta cuenta_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuenta
    ADD CONSTRAINT cuenta_pkey PRIMARY KEY (id_cuenta);


--
-- TOC entry 3191 (class 2606 OID 16412)
-- Name: extracto extracto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.extracto
    ADD CONSTRAINT extracto_pkey PRIMARY KEY (id);


--
-- TOC entry 3193 (class 2606 OID 16418)
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id_persona);


-- Completed on 2023-06-21 19:20:53

--
-- PostgreSQL database dump complete
--

-- Completed on 2023-06-21 19:20:53

--
-- PostgreSQL database cluster dump complete
--

